server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123abc
    url: jdbc:mysql://localhost:13306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 1
      read-only: false

logging:
  file:
    name: ./demo.log
  level:
    com.hh: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hh.**.entity
